// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      throw UnsupportedError(
        'DefaultFirebaseOptions have not been configured for web - '
        'you can reconfigure this by running the FlutterFire CLI again.',
      );
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBp0fDpJsLl9f_wGlpD5FNPOrhSmrhaIfg',
    appId: '1:689042038719:android:c50b9cac81a706dcd94b0a',
    messagingSenderId: '689042038719',
    projectId: 'ditonton-14934',
    databaseURL: 'https://ditonton-14934-default-rtdb.asia-southeast1.firebasedatabase.app',
    storageBucket: 'ditonton-14934.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBTru7jIFDAqNG6ODWxpsZNteZk81_Suew',
    appId: '1:689042038719:ios:fa0879e0e5d5931ad94b0a',
    messagingSenderId: '689042038719',
    projectId: 'ditonton-14934',
    databaseURL: 'https://ditonton-14934-default-rtdb.asia-southeast1.firebasedatabase.app',
    storageBucket: 'ditonton-14934.appspot.com',
    iosClientId: '689042038719-eoe0qn4l8iejlcb1gs6lii57bq91obbm.apps.googleusercontent.com',
    iosBundleId: 'com.dicoding.ditonton',
  );
}
